### ISSUE TITLE
Capture container logs on deployment failure

### ISSUE THREAD

**Issue by raphaelquati** [jenkinsci/azure-container-agents-plugin#21]
Capturing the log, before initialize a new deployment would be great.

**Comment by zackliu** [comment]
New version(0.4.0) will capture logs when deploying.
What logs do you want before a new deployment?

**Comment by raphaelquati** [comment]
[In this link](https://stackoverflow.com/questions/47935693/docker-container-timeout-windowsservercore-azure-aci) I describe an error with my docker image in Azure.

The container doesn't run correctly in Azure. So the plugin doesn't  connect to container successfully. 
It terminates the container group, desctroy the container, and start a new deploy again. It's hard to catch the logs (at Azure console).

The actual logs (example)

```
    Dec 16, 2017 3:34:23 PM com.microsoft.jenkins.containeragents.aci.AciCloud$1 call
    WARNING: AciCloud: Provision agent windows-aci-khcn8 failed: Deployment timeout
    Dec 16, 2017 3:34:23 PM okhttp3.internal.platform.Platform log
    INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
    Dec 16, 2017 3:34:24 PM com.microsoft.jenkins.containeragents.aci.AciService deleteAciContainerGroup
    INFO: Delete ACI Container Group: windows-aci-khcn8 successfully
    Dec 16, 2017 3:34:27 PM hudson.slaves.NodeProvisioner$2 run
    WARNING: Unexpected exception encountered while provisioning agent Windows ACI
    java.lang.Exception: java.lang.Exception: Deployment timeout
    	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:131)
    	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:80)
    	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    	at java.util.concurrent.FutureTask.run(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.Exception: Deployment timeout
    	at com.microsoft.jenkins.containeragents.aci.AciService.createDeployment(AciService.java:122)
    	at com.microsoft.jenkins.containeragents.aci.AciContainerTemplate.provisionAgents(AciContainerTemplate.java:107)
    	at com.microsoft.jenkins.containeragents.aci.AciCloud$1.call(AciCloud.java:104)
    	... 6 more
```

The new version (0.4.0) will capture logs in this situation?

**Comment by zackliu** [comment]
Yes, once the deployment time exceed the half of your time limit, we will capture logs for you every 30 sec. And if deployment succeed but launching failed, we will capture logs as well.

**Comment by raphaelquati** [comment]
Great! Thank you!
